services:
  notificationservice.web:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    container_name: ${DOCKER_REGISTRY-}notificationservice.web
    build:
      context: .
      dockerfile: NotificationService.Web/Dockerfile
    ports:
      - "8082:5001"
        
  rediscache:
    container_name: "rediscache"
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
  
